[workspace]

resolver = "2"
exclude = ["openh264-rs"]
members = [
    "server",
    "client",
]



[profile.dev.package."*"]
# Turn on a small amount of optimisation in Development mode.
opt-level = 3
debug=true
